import { Emoji } from './types/game';

// Harry Potter themed emojis for Horcrux creation
export const EMOJI_LIST: Emoji[] = [
  // Magical Objects & Artifacts
  { id: '1', emoji: '🪄', name: 'wand' },
  { id: '2', emoji: '📿', name: 'locket' },
  { id: '3', emoji: '👑', name: 'diadem' },
  { id: '4', emoji: '💍', name: 'ring' },
  { id: '5', emoji: '🏆', name: 'cup' },
  { id: '6', emoji: '📚', name: 'diary' },
  { id: '7', emoji: '🐍', name: 'snake' },
  { id: '8', emoji: '⚡', name: 'scar' },

  // Dark Arts & Magic
  { id: '9', emoji: '🌑', name: 'dark' },
  { id: '10', emoji: '💀', name: 'death' },
  { id: '11', emoji: '🔮', name: 'crystal' },
  { id: '12', emoji: '🕯️', name: 'candle' },
  { id: '13', emoji: '👻', name: 'spirit' },
  { id: '14', emoji: '🦇', name: 'bat' },
  { id: '15', emoji: '🕷️', name: 'spider' },
  { id: '16', emoji: '🌙', name: 'moon' },

  // Hogwarts & Places
  { id: '17', emoji: '🏰', name: 'castle' },
  { id: '18', emoji: '🌲', name: 'forest' },
  { id: '19', emoji: '🏠', name: 'house' },
  { id: '20', emoji: '🚪', name: 'chamber' },
  { id: '21', emoji: '🗝️', name: 'key' },
  { id: '22', emoji: '🔒', name: 'vault' },
  { id: '23', emoji: '⛰️', name: 'cave' },
  { id: '24', emoji: '🌊', name: 'lake' },

  // Magical Creatures
  { id: '25', emoji: '🦅', name: 'eagle' },
  { id: '26', emoji: '🦁', name: 'lion' },
  { id: '27', emoji: '🐉', name: 'dragon' },
  { id: '28', emoji: '🦌', name: 'stag' },
  { id: '29', emoji: '🐺', name: 'wolf' },
  { id: '30', emoji: '🦉', name: 'owl' },
  { id: '31', emoji: '🐀', name: 'rat' },
  { id: '32', emoji: '🐈‍⬛', name: 'cat' },

  // Elements & Nature
  { id: '33', emoji: '🔥', name: 'fire' },
  { id: '34', emoji: '💧', name: 'water' },
  { id: '35', emoji: '🌪️', name: 'wind' },
  { id: '36', emoji: '⛈️', name: 'storm' },
  { id: '37', emoji: '❄️', name: 'ice' },
  { id: '38', emoji: '⭐', name: 'star' },
  { id: '39', emoji: '☄️', name: 'comet' },
  { id: '40', emoji: '🌟', name: 'magic' },

  // Potions & Ingredients
  { id: '41', emoji: '🧪', name: 'potion' },
  { id: '42', emoji: '🍄', name: 'mushroom' },
  { id: '43', emoji: '🌿', name: 'herb' },
  { id: '44', emoji: '🍃', name: 'leaf' },
  { id: '45', emoji: '🌹', name: 'rose' },
  { id: '46', emoji: '🥀', name: 'thorn' },
  { id: '47', emoji: '🍯', name: 'honey' },
  { id: '48', emoji: '🧂', name: 'salt' },

  // Mystical & Ancient
  { id: '49', emoji: '📜', name: 'scroll' },
  { id: '50', emoji: '⚱️', name: 'urn' },
  { id: '51', emoji: '🗿', name: 'stone' },
  { id: '52', emoji: '⚰️', name: 'tomb' },
  { id: '53', emoji: '🔱', name: 'trident' },
  { id: '54', emoji: '⚔️', name: 'sword' },
  { id: '55', emoji: '🛡️', name: 'shield' },
  { id: '56', emoji: '🏺', name: 'vessel' },

  // Time & Memory
  { id: '57', emoji: '⏳', name: 'time' },
  { id: '58', emoji: '🧠', name: 'memory' },
  { id: '59', emoji: '💭', name: 'thought' },
  { id: '60', emoji: '❤️', name: 'soul' },

  // Additional Magical Items
  { id: '61', emoji: '🎭', name: 'mask' },
  { id: '62', emoji: '🎪', name: 'tent' },
  { id: '63', emoji: '🎨', name: 'paint' },
  { id: '64', emoji: '🎯', name: 'target' },
  { id: '65', emoji: '🎲', name: 'dice' },
  { id: '66', emoji: '🎰', name: 'slot' },
  { id: '67', emoji: '🧿', name: 'eye' },
  { id: '68', emoji: '🪬', name: 'hamsa' },

  // More Creatures
  { id: '69', emoji: '🦂', name: 'scorpion' },
  { id: '70', emoji: '🦎', name: 'lizard' },
  { id: '71', emoji: '🐢', name: 'turtle' },
  { id: '72', emoji: '🐸', name: 'frog' },
  { id: '73', emoji: '🦋', name: 'butterfly' },
  { id: '74', emoji: '🐛', name: 'worm' },
  { id: '75', emoji: '🦗', name: 'cricket' },
  { id: '76', emoji: '🕊️', name: 'dove' },

  // Celestial & Cosmic
  { id: '77', emoji: '🌞', name: 'sun' },
  { id: '78', emoji: '🌝', name: 'face' },
  { id: '79', emoji: '🌛', name: 'crescent' },
  { id: '80', emoji: '🌚', name: 'newmoon' },
  { id: '81', emoji: '🌕', name: 'fullmoon' },
  { id: '82', emoji: '🌖', name: 'waning' },
  { id: '83', emoji: '🌗', name: 'quarter' },
  { id: '84', emoji: '🌘', name: 'waxing' },

  // Plants & Flora
  { id: '85', emoji: '🌺', name: 'hibiscus' },
  { id: '86', emoji: '🌻', name: 'sunflower' },
  { id: '87', emoji: '🌷', name: 'tulip' },
  { id: '88', emoji: '🌱', name: 'seedling' },
  { id: '89', emoji: '🌾', name: 'grain' },
  { id: '90', emoji: '🍀', name: 'clover' },
  { id: '91', emoji: '🌵', name: 'cactus' },
  { id: '92', emoji: '🎋', name: 'bamboo' },

  // Gems & Minerals
  { id: '93', emoji: '💎', name: 'gem' },
  { id: '94', emoji: '💠', name: 'diamond' },
  { id: '95', emoji: '🔷', name: 'blue' },
  { id: '96', emoji: '🔶', name: 'orange' },
  { id: '97', emoji: '🟣', name: 'purple' },
  { id: '98', emoji: '🟢', name: 'green' },
  { id: '99', emoji: '🔴', name: 'red' },
  { id: '100', emoji: '🟡', name: 'yellow' },

  // Weather & Sky
  { id: '101', emoji: '🌈', name: 'rainbow' },
  { id: '102', emoji: '☁️', name: 'cloud' },
  { id: '103', emoji: '⛅', name: 'partly' },
  { id: '104', emoji: '🌤️', name: 'sunny' },
  { id: '105', emoji: '🌥️', name: 'cloudy' },
  { id: '106', emoji: '🌦️', name: 'rain' },
  { id: '107', emoji: '🌧️', name: 'shower' },
  { id: '108', emoji: '⛈️', name: 'thunder' },

  // Tools & Instruments
  { id: '109', emoji: '🔨', name: 'hammer' },
  { id: '110', emoji: '⚒️', name: 'tools' },
  { id: '111', emoji: '🛠️', name: 'wrench' },
  { id: '112', emoji: '⚙️', name: 'gear' },
  { id: '113', emoji: '🔧', name: 'spanner' },
  { id: '114', emoji: '🪓', name: 'axe' },
  { id: '115', emoji: '⛏️', name: 'pick' },
  { id: '116', emoji: '🗡️', name: 'dagger' },

  // Books & Knowledge
  { id: '117', emoji: '📖', name: 'book' },
  { id: '118', emoji: '📕', name: 'closed' },
  { id: '119', emoji: '📗', name: 'green' },
  { id: '120', emoji: '📘', name: 'blue' },
  { id: '121', emoji: '📙', name: 'orange' },
  { id: '122', emoji: '📔', name: 'notebook' },
  { id: '123', emoji: '📓', name: 'journal' },
  { id: '124', emoji: '📒', name: 'ledger' },
];

// Harry Potter themed words for Horcrux creation
export const WORD_LIST: string[] = [
  // 5 letters - Magical basics
  'magic',
  'spell',
  'wand',
  'ghost',
  'death',
  'power',
  'stone',
  'heart',
  'snake',
  'diary',
  'sword',
  'flame',
  'curse',
  'charm',
  'tower',
  'cloak',
  'blood',
  'soul',
  'dark',
  'light',
  'witch',
  'beast',
  'troll',
  'giant',
  'dwarf',
  'fairy',
  'gnome',
  'pixie',
  'bogey',
  'demon',
  'angel',
  'raven',
  'eagle',
  'crown',
  'jewel',
  'pearl',
  'amber',
  'coral',
  'ivory',
  'ebony',
  'lunar',
  'solar',
  'comet',
  'orbit',
  'phase',
  'eclipse',
  'storm',
  'frost',
  'blaze',
  'spark',

  // 6 letters - Magical objects & places
  'locket',
  'diadem',
  'castle',
  'forest',
  'chamber',
  'memory',
  'spirit',
  'shadow',
  'dragon',
  'wizard',
  'muggle',
  'seeker',
  'beater',
  'keeper',
  'golden',
  'silver',
  'mirror',
  'portal',
  'secret',
  'hidden',
  'ancient',
  'mystic',
  'oracle',
  'temple',
  'shrine',
  'throne',
  'scepter',
  'amulet',
  'talisman',
  'scroll',
  'grimoire',
  'codex',
  'potion',
  'elixir',
  'remedy',
  'poison',
  'venom',
  'antidote',
  'healing',
  'cursed',
  'warden',
  'keeper',
  'guardian',
  'sentinel',
  'protector',
  'defender',
  'warrior',
  'knight',

  // 7 letters - Advanced magic
  'phoenix',
  'unicorn',
  'centaur',
  'mystery',
  'destiny',
  'prophecy',
  'magical',
  'enchant',
  'bewitch',
  'conjure',
  'vanish',
  'protect',
  'destroy',
  'forever',
  'eternal',
  'immortal',
  'powerful',
  'forbidden',
  'secrets',
  'treasure',
  'artifact',
  'relic',
  'legend',
  'history',
  'journey',
  'quest',
  'mission',
  'calling',
  'purpose',
  'destiny',
  'fortune',
  'alchemy',
  'sorcery',
  'wizardry',
  'witchcraft',
  'necromancy',
  'divination',
  'illusion',
  'phantom',
  'specter',
  'wraith',
  'banshee',
  'vampire',
  'werewolf',
  'chimera',
  'griffin',
  'basilisk',
  'manticore',
  'hydra',
  'kraken',
  'leviathan',
  'behemoth',
  'colossus',
  'titan',
  'goliath',

  // 8 letters - Complex magical concepts
  'patronus',
  'animagus',
  'levitate',
  'hallows',
  'deathly',
  'wandlore',
  'prophecies',
  'herbology',
  'potions',
  'charms',
  'defense',
  'transfigure',
  'metamorph',
  'transform',
  'transmute',
  'enchantment',
  'incantation',
  'invocation',
  'summoning',
  'banishment',
  'exorcism',
  'blessing',
  'sanctify',
  'consecrate',
  'purify',
  'cleanse',
  'absolve',
  'redeem',
  'salvation',
  'damnation',
  'perdition',
  'oblivion',
  'eternity',
  'infinity',
  'immortality',
  'mortality',
  'humanity',
  'divinity',
  'sanctity',
  'holiness',
  'darkness',
  'lightness',
  'brightness',
  'radiance',
  'luminous',
  'glowing',
  'shimmering',
  'sparkling',

  // 9 letters - Epic magical terms
  'philosopher',
  'sorcerer',
  'alchemist',
  'apparition',
  'fidelius',
  'unbreakable',
  'veritaserum',
  'polyjuice',
  'amortentia',
  'gillyweed',
  'mandrake',
  'wolfsbane',
  'butterbeer',
  'firewhisky',
  'chocolate',
  'cauldron',
  'broomstick',
  'quidditch',
  'remembrall',
  'timeturner',
  'pensieve',
  'enchanter',
  'conjurer',
  'illusionist',
  'necromancer',
  'summoner',
  'elementalist',
  'pyromancer',
  'cryomancer',
  'geomancer',
  'aeromancer',
  'hydromancer',
  'astrologer',
  'astronomer',
  'cosmologist',
  'metaphysician',
  'theologian',
  'philosopher',
  'scholar',
  'sage',
  'mystic',
  'prophet',
  'visionary',
  'clairvoyant',
  'telepath',
  'empath',
  'medium',
  'channeler',
  'spiritualist',
  'occultist',
];
